
@ContosoPizza_HostAddress = http://localhost:5237

# GET {{ContosoPizza_HostAddress}}/products/
# Accept: application/json

# POST {{ContosoPizza_HostAddress}}/products/
# Content-Type: application/json

# {
#     "name": "New Extra Extra Combo",
#     "price": 50.99
# }


PUT {{ContosoPizza_HostAddress}}/products/6
Content-Type: application/json

{
    "id": "6",
    "name": "Personal Party Combo",
    "price": 10.99
}

# DELETE {{ContosoPizza_HostAddress}}/products/4

###